---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
      runs-on: ubuntu-latest
      name: release
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.19
        - name: build windows amd64
          run: GOOS=windows GOARCH=amd64 go build -o go-gin-poc-win-x64.exe cmd/go-gin-poc/main.go
        - name: build windows i386
          run: GOOS=windows GOARCH=386 go build -o go-gin-poc-win.exe cmd/go-gin-poc/main.go
        - name: build linux amd64
          run: GOOS=linux GOARCH=amd64 go build -o go-gin-poc-linux-x64 cmd/go-gin-poc/main.go
        - name: build linux i386
          run: GOOS=linux GOARCH=386 go build -o go-gin-poc-linux cmd/go-gin-poc/main.go
        - name: build linux arm
          run: GOOS=linux GOARCH=arm go build -o go-gin-poc-linux-arm cmd/go-gin-poc/main.go
        - name: build linux arm64
          run: GOOS=linux GOARCH=arm64 go build -o go-gin-poc-linux-arm64 cmd/go-gin-poc/main.go
        - name: build mac amd64
          run: GOOS=darwin GOARCH=amd64 go build -o go-gin-poc-mac-amd64 cmd/go-gin-poc/main.go
        - name: build mac arm64
          run: GOOS=darwin GOARCH=arm64 go build -o go-gin-poc-mac-arm64 cmd/go-gin-poc/main.go
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
              go-gin-poc-*