name: build and tests

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v3
        - name: Setup go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        - run: make build
        - run: make test
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          with:
            args: >
              -Dsonar.organization=brunoshiroma
              -Dsonar.projectKey=brunoshiroma_go-proxy
              -Dsonar.go.coverage.reportPaths=coverage.out
              -Dsonar.sources=cmd,internal
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
